### ISSUE TITLE
Version 3 CLI Squad

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/zowe-cli#1740]
Epic for the squad to link all the relevant work that the squad intend to prepare for the V3 release so we can track how far we are.
```[tasklist]
### Tasks
- [ ] https://github.com/zowe/zowe-cli/issues/1702
- [ ] https://github.com/zowe/zowe-cli/issues/1695
- [ ] https://github.com/zowe/zowe-cli/issues/1703
- [ ] https://github.com/zowe/zowe-cli/issues/1694
- [ ] https://github.com/zowe/zowe-cli/issues/1696
- [ ] https://github.com/zowe/zowe-cli/issues/1698
- [ ] https://github.com/zowe/zowe-cli/issues/1699
```
