### ISSUE TITLE
24PI1 Planning

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-cli#1971]
# Zowe CLI Squad - 24PI1 - (2024/01/23 - 2024/04/22)

## V3 Preparation
Implement planned changes for V3 and continue to publish pre-release versions to npm.
- [x] https://github.com/zowe/zowe-cli/issues/1703
- [ ] https://github.com/zowe/zowe-cli/issues/1801
- [x] https://github.com/zowe/zowe-cli/issues/1699
- [x] https://github.com/zowe/zowe-cli/issues/1689 - Consider functionality in V3

## Config Usability
Continue to improve team config robustness and flexibility.
- [x] https://github.com/zowe/zowe-cli/issues/2005
- [ ] [**_Stretch_**] https://github.com/zowe/zowe-cli/issues/1858
- [ ] [**_Stretch_**] https://github.com/zowe/zowe-cli/issues/1899 - Initial design
- [x] https://github.com/zowe/zowe-cli/issues/1797
- [ ] [Stretch] https://github.com/zowe/zowe-cli/issues/1770

## Extension Support
Ensure that extenders have access to the tools they need to interact with team config and secure credential storage.
- [ ] [**_Stretch_**] https://github.com/zowe/zowe-cli/issues/1987
- [x] https://github.com/zowe/zowe-cli/issues/1964
- [ ] https://github.com/zowe/zowe-cli/issues/1882

## V3 Open Source CLI Plug-in Updates and Conformance - *Added February 1, 2024*
Update the open source Zowe CLI plug-ins and achieve V3 conformance.
- [x] [IBM® CICS® Plug-in for Zowe CLI](https://github.com/zowe/cics-for-zowe-client/issues/101)
- [x] [IBM® Db2® Database Plug-in for Zowe™ CLI](https://github.com/zowe/zowe-cli-db2-plugin/issues/141)
- [x] [IBM® MQ Plug-in for Zowe CLI](https://github.com/zowe/zowe-cli-mq-plugin/issues/60)
- [x] [z/OS FTP Plug-in for Zowe CLI](https://github.com/zowe/zowe-cli-ftp-plugin/issues/153)
- [x] Update the IBM® IMS™ Plug-in for Zowe CLI readme with a notice that the plug-in is discontinued, publish the plug-in with the new readme, and archive the repository.
- [x] [Stretch] [Make V3 updates to the Zowe CLI Sample Plug-in](https://github.com/zowe/zowe-cli-sample-plugin/issues/96)

## High Priority and Upvoted Defects and Enhancements
Continue to responsibly address backlog items according to perceived priority and community interest.
- [ ] [**_Stretch_**] https://github.com/zowe/zowe-cli/issues/1566
- [ ] [Stretch] https://github.com/zowe/zowe-cli/issues/1469
- [ ] [Stretch] https://github.com/zowe/zowe-cli/issues/1872

## SDK Conformance and LTS status
Work with the Onboarding Squad and the IntelliJ Explorer Squad to develop Zowe client SDK conformance criteria and ensure that the Node.JS and Python Zowe Client SDKs achieve conformance.
- [ ] https://github.com/zowe/zowe-cli/issues/1675

## OpenSSF Best Practices Badge
Support the ongoing Zowe OpenSSF Best Practices audit process.
- [ ] https://github.com/zowe/zowe-cli/issues/1352
- [ ] [Stretch] https://github.com/zowe/zowe-cli/issues/1760
- [ ] [Stretch] https://github.com/zowe/zowe-cli/issues/1761
- [ ] [Stretch] https://github.com/zowe/zowe-cli/issues/1762
  - Update shared Zowe spreadsheet with the latest information on the Zowe CLI project

#### Helpful links for OpenSSF Best Practices Badge criteria:
- Passing: https://bestpractices.coreinfrastructure.org/en/criteria/0
- Silver: https://bestpractices.coreinfrastructure.org/en/criteria/1
- Gold: https://bestpractices.coreinfrastructure.org/en/criteria/2

# Zowe CLI / Zowe SDK Roadmap

## Ensure that Zowe VS Code Extensions can Share Access to zowe.schema.json with Zowe CLI
- _What problem are you solving?_
  - Zowe CLI overwrites team config profile entries contributed by Zowe Explorer extensions, preventing those extensions from being able to properly access profiles from a user's team config.
- _What are you doing to solve it?_
  - Schema profile additions will be synchronized in such a way that both VS Code extensions and Zowe CLI plug-ins can contribute to a schema without removing the profiles contributed by the other.
- _When do you plan to start the work?_
  - **CY23Q4**
- _When do you plan to deliver the solution?_
  - **CY24Q1** 

## Gold OpenSSF Best Practices Badge (Formerly CII Best Practices Badge)
- _What problem are you solving?_
  - The Zowe Project has not earned the gold OpenSSF Best Practices Badge, a requirement from LF/OMP that ensures the Open Source project satisfies FLOSS (Free/Libre & Open Source Software) [Best Practices criteria](https://bestpractices.coreinfrastructure.org/en/criteria)
- _What are you doing to solve it?_
  - Review requirements and take necessary actions to satisfy them for the gold badge level 
- _When do you plan to start the work?_
  - **CY22Q3**
- _When do you plan to deliver the solution?_
  - **CY24Q1** Achieve Passing Badge
  - **CY24Q4** Achieve Silver Badge
  - **CY25Q4** Achieve Gold Badge

## SDK Conformance and LTS Status
- _What problem are you solving?_
  - Mainframe developers are interested in extending the existing SDKs in order to create applications for their services
- _What are you doing to solve it?_
  - Solidify the SDK Conformance guidelines for:
    - New Services (like CICS SDK)
    - New Programming languages (like Kotlin SDK)
  - Prepare the SDKs technically and logistically for conformance
  - Determine if existing SDKs are conformant and communicate conformance gaps for prioritization
  - Release the Zowe Client Node.js SDK as LTS
- _When do you plan to start the work?_
  - **CY23Q2**
- _When do you plan to deliver the solution?_
  - **CY23Q4** (delayed until CY24Q2)
