### ISSUE TITLE
Review Contribution Guidelines for Currency and Requirements

### ISSUE THREAD

**Issue by BrandonJenkins14** [zowe/zowe-cli#354]
**Canonical:**
As a contributor to Zowe CLI, I want to understand what is a requirement vs. what is just a guideline to be Zowe conformant. I also want to be sure that the guidelines are current so that my plug-in is compatible and consistent with other components. 

**Tasks:**
Our [conformance criteria](https://github.com/zowe/zowe-cli/blob/conformance/docs/cli-conformance.md   ) asks contributors to adhere to requirements in the following documents. Review each to A. Ensure that they are technically correct and current and B. Adjust language throughout to clarify hard requirements vs soft guidelines:

- [ ] Review https://github.com/zowe/zowe-cli/blob/conformance/CONTRIBUTING.md  
      Assigned: 
      Status: Not started

- [ ] Review https://github.com/zowe/zowe-cli/blob/master/docs/PackagesAndPluginGuidelines.md  
      Assigned: 
      Status: Not started

- [ ] Review https://github.com/zowe/zowe-cli/blob/master/docs/CommandFormatStandards.md   
      Assigned: 
      Status: Not started

- [ ] Review https://github.com/zowe/zowe-cli/blob/master/docs/MaintainerVersioning.md   
      Assigned: 
      Status: Not started

- [ ] Our conformance critera don't mention this file, but should still be checked for currency - https://github.com/zowe/zowe-cli/blob/conformance/docs/TESTING.md   
      Assigned: 
      Status: Not started

- [ ] Our conformance critera don't mention this file, but should still be checked for currency -  https://github.com/zowe/zowe-cli/blob/conformance/docs/ProfileGuidelines.md
      Assigned: 
      Status: Not started

**Comment by BrandonJenkins14** [comment]
+ Consider which hard requirements can be automated as part of the conformance program testing process. (Remember, this review must be done for every new contribution, which could be many).

**Comment by BrandonJenkins14** [comment]
@JTonda I think this issue might have been completed as part of gathering our conformance criteria. We should verify with the squad.

**Comment by gejohnston** [comment]
This issue is outdated. Conformance guidelines have been revised at least twice since the creation of this issue. If new concerns exist in the current conformance guidelines, they should opened agains the conformance document which lives in a separate repository.

https://github.com/openmainframeproject/foundation/blob/main/zowe_conformance/test_evaluation_guide_table.md
