### ISSUE TITLE
CLI and APIML integration

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#43]
_From @JTonda on August 27, 2018 17:43_

Zowe CLI Core users would like to access APIs through the APIML so that they can benefit from its various features including high-availability, scalability, and dynamic API discovery.

Profiles can alter the base URL that is used to access the service. In this case, the user can change the URL to the gateway URL (e.g. from https://host1:port1/zosmf/ to https://host2:port2/api/v1/zosmf/).
* This approach requires a base URL of the service to be known to the user (e.g. displayed in API Catalog) - new story for APIML
* z/OSMF direct URL: https://host:port/zosmf/restjobs/1.0/...
Gateway URL: https://host:port/api/v1/zosmfxx/restjobs/1.0/...
* Universal solution: Instead of baseUrl provide hostname, port, basePath (terms like baseUrl or basePath are defined in https://swagger.io/docs/specification/2-0/api-host-and-base-path/) - consider IPv6 addresses and everything that can be in a URL
* A --base-path | --bp option is added to profiles. If not specified it should be what is currently used to access the APIs directly.

Note:
API mediation layer needed on DE20

*Accept feature with PM
13 point story

_Copied from original issue: gizafoundation/brightside#200_

# Tasks
- [x] System Tests: update test properties and test environment setup to be able to execute the tests with and without base path
   Status: Not Started
   Assigned: @ChrisBoehmCA 
- [x] Clean up system test doc
   Status: Not Started
   Assigned: @AHumanFromCA 
- [x] Update the RestClient and Session to use basePath in Imperative
   Status: Done
   Assigned: @gejohnston 
- [x] Update zowe-cli to have a CLI option for "--base-path" (and profile field too)
   Status: Completed
   Assigned: @PeteSwauger 
- [x] Doc everything (Not sure what doc everything means, but I know that Zowe CLI user guide needs updated. Likely Imperative updates). 
   Status: Not Started
   Assigned: @JamesBauman 
- [x] Manually test command groups provisioning in zowe-cli
   Status: Completed
   Assigned: @tucker01 
- [x] Manually test command groups zos-files, zos-jobs, zos-console in zowe-cli
   Status: Completed
   Assigned: @PeteSwauger 
- [x] Manually test command groups zosmf, zos-tso in zowe-cli
   Status: Completed
   Assigned: @gejohnston @PeteSwauger
- [x] Verify that imperative changes do not break CICS plugin
   Status: Completed
   Assigned: @PeteSwauger

**Comment by tucker01** [comment]
Normally, the base "path" is "/zosmf/" (followed by something like "restjobs/jobs/"), which is hard-coded in our API classes (e.g. "/zosmf/restjobs/jobs"). We'll have to adjust those to include only the route. 

@plavjanik, is this the only transformation that can occur? Is it possible that Gateway users can transform the entire route/URI? (e.g. "/zosmf/restjobs/jobs" -> "/super/cool/jobs")

**Comment by tucker01** [comment]
With recent pending changes, we'll also need to add the option to our "zosmf connection options" so it can be specified via CLI/ENV/prof.

**Comment by plavjanik** [comment]
@tucker01 I have discussed this with Done and we will add the `/zosmf/` in the URL. We will not use versioning at the gateway level since the z/OSMF uses a different schema for versioning. The URL z/OSMF at the gateway will look like: `https://host:port/api/zosmfservice1/zosmf/restjobs/jobs/...`.

Our recommendation is to use `/api/vn/serviceId` where _n_ is a major version of the API, or just `/api/serviceId` if the service does have APIs versioned differently. Currently, we just recommend it but we have stories in the backlog to enforce it.
