### ISSUE TITLE
Publish json-config-next with next tag for validation

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-cli#910]
Imperative:
* [x] Merge changes from master into next & json-config-next (Done - https://github.com/zowe/imperative/pull/501, https://github.com/zowe/imperative/pull/502, https://github.com/zowe/imperative/pull/530)
* [x] Merge enhancement for deprecated commands (Done - https://github.com/zowe/imperative/pull/529)
* [x] Merge fix for secure properties shown in config list output (Done - https://github.com/zowe/imperative/pull/532)
* [x] Revert changes to NPM scripts for Git install (Done - https://github.com/zowe/imperative/pull/452/commits/26c2f03959896418a4d595107636b1ebe1b1f8f9)
* [x] Update changelog (Pending review - draft is [here](https://github.com/zowe/imperative/blob/json-config-next/CHANGELOG.md#recent-changes))
* [x] Merge the big PR 😛 (https://github.com/zowe/imperative/pull/452)
* [x] Publish fix for https://github.com/zowe/imperative/issues/533 (Done - https://github.com/zowe/imperative/pull/534)

Zowe CLI:
* [x] Merge fixes for daemon mode (Done - #928)
* [x] Merge changes from master into next & json-config-next (Done - #898)
* [x] Merge doc update into next (Ready to merge after #898 is merged and DCO is fixed - #877)
* [x] Update Imperative dependency after published to NPM
* [x] Update changelog (Pending review - draft is [here](https://github.com/zowe/zowe-cli/blob/json-config-next/packages/cli/CHANGELOG.md#recent-changes))
* [x] Merge the 2nd big PR (Ready to merge - #930)
* [x] Update readme in master (Ready to merge - #932)

**Comment by dkelosky** [comment]
for draft on PR,
> Enhancement: Added support for secure credential storage without any plug-ins required. Include the "keytar" package as a dependency in your CLI to make use of it.

Is this an "Enhancement" or "Breaking" ? 😄

**Comment by t1m0thyj** [comment]
> for draft on PR,
> 
> > Enhancement: Added support for secure credential storage without any plug-ins required. Include the "keytar" package as a dependency in your CLI to make use of it.
> 
> Is this an "Enhancement" or "Breaking" ? 😄

@dkelosky Not sure if its breaking - we continue to support credentials that were stored with the old SCS credential manager. 😸

**Comment by dkelosky** [comment]
gotcha - I mean breaking in terms of operations, since the SCS isn't needed to be separately installable any longer.  With your comments though, I think it should be left as is. 

Thanks!

**Comment by t1m0thyj** [comment]
Early access features available in "next" release on NPM: https://www.npmjs.com/package/@zowe/cli#early-access-features

`zowex` binary for daemon mode available here: https://github.com/zowe/zowe-cli/releases/tag/native-v0.2.0
